; objectTypeIDs:
;   00-3F general objects.
;   40-7F special objects.
;   80-BF text of general object.
;   C0-FD properties
TID_TEXT = $80

TID_BABA = $00
TID_FLAG = $01
TID_WALL = $02
TID_ROCK = $03
TID_WATR = $04
TID_SKUL = $05
TID_LAVA = $06
TID_KEKE = $07
TID_LOVE = $08

TID_ISLAND = $3E
TID_LINK = $3F

TID_OBJ_MASK = $3F

TID_IS   = $40

TID_PROP      = TID_TEXT | $40
TID_YOU       = TID_PROP | $00
TID_WIN       = TID_PROP | $01
TID_STOP      = TID_PROP | $02
TID_PUSH      = TID_PROP | $03
TID_SINK      = TID_PROP | $04
TID_DEFEAT    = TID_PROP | $05
TID_HOT       = TID_PROP | $06
TID_MELT      = TID_PROP | $07
TID_MOVE      = TID_PROP | $08

TID_DESTROYED = $FE
TID_NO_OBJECT = $FF

DIR_DOWN  = 0
DIR_UP    = 1
DIR_LEFT  = 2
DIR_RIGHT = 3
DIR_NONE  = $FF

FLAGN_YOU  = 7
FLAGN_MOVE = 3
FLAGN_PUSH = 2
FLAGN_STOP = 1
FLAGN_WIN  = 0

FLAG2N_SINK = 0
FLAG2N_DEFEAT = 1
FLAG2N_HOT = 2
FLAG2N_MELT = 3

FLAG_YOU  = 1 << FLAGN_YOU
FLAG_MOVE = 1 << FLAGN_MOVE
FLAG_PUSH = 1 << FLAGN_PUSH
FLAG_STOP = 1 << FLAGN_STOP
FLAG_WIN  = 1 << FLAGN_WIN

FLAG2_SINK = 1 << FLAG2N_SINK
FLAG2_DEFEAT = 1 << FLAG2N_DEFEAT
FLAG2_HOT = 1 << FLAG2N_HOT
FLAG2_MELT = 1 << FLAG2N_MELT